### PR TITLE
Fixed some bugs and added images to the ItineraryBanner and smal features

### LINKED ISSUE #232: #ISSUE 216 Refactor UI to use Firestore Profile

### PR DESCRIPTION
**Pull request by engjellismaili**
### Added Images to ItineraryBanner. Closes #232 

> `ItineraryBanners` now fetch images that are store in `Storage`. If no image is found, display a default one.

> Fixed tests that uses `ItineraryBanner` to now add `ProfileViewModel` / `ImageRepository`

### Smal features

> The `ItineraryBanner` now display the name of the creator. The user that created an itinerary is fetched from `Firestore`, and his name is displayed.

> `WanderPoints` now aren't hardcoded anymore. They are now based on the number of likes for each itinerary created.

### Small issues fixed 

> The size of the image that can be fetched from `Firebase` has been modified. This value can be modified anytime.

> The active profile wasn't correctly set in the `SignInRepository`.

> When an `Itinerary` was liked, it wasn't correctly register as "Liked". Small fix that now works.

> MAJOR TODO : The `AppModuleTest` is temporarly modified because it makes some tests fails. One potential reason is the fact that the `AppModuleTest` file initizalise the `Repositories` / `ViewModels`, that sometimes are initialized again in some tests. We must find a way to either "reset" the `AppModule` after testing the `AppModuleTest`, or modify tests to mock each Repo / VM.

### CODE REVIEW

File: app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt [hunk 1]
```diff
@@ -129,7 +130,10 @@ class MainActivity : ComponentActivity() {
         signInIntent,
         locationClient,
         savedItinerariesDataStore,
-        applicationContext)
+        applicationContext,
+        FirebaseAuth.getInstance(),
+        FirebaseFirestore.getInstance(),
+        FirebaseStorage.getInstance())
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt:137]: Fantastic, truly brilliant code (jk I wrote this part)

File: app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt [hunk 2]
```diff
@@ -46,15 +51,22 @@ class ProfileRepositoryImpl(db: FirebaseFirestore) : ProfileRepository {
...
+                  Log.w("ProfileRepositoryImpl", exception)
+                  continuation.resumeWithException(exception)
+                }
           }
           emit(allProfiles)
         }
-        .catch { emit(listOf()) }
+        .catch {
+          Log.w("ProfileRepositoryImpl", it)
+          emit(listOf())
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt:68]: Same here with the `it`.

I've started returning `emptyList()` instead of `listOf()` in my code since I find it more readable, but this is just a nitpick. Behavior looks correct

File: app/src/main/java/com/github/wanderwise_inc/app/di/AppModule.kt [hunk 3]
```diff
@@ -47,19 +49,21 @@ object AppModule {
...
   ) {
     this.imageLauncher = imageLauncher
     this.signInLauncher = signInLauncher
     this.sinInIntent = sinInIntent
     this.locationClient = locationClient
     this.savedItinerariesDataStore = savedItinerariesDataStore
     this.context = context
+    this.firebaseAuth = firebaseAuth
+    this.db = firebaseFirestore
+    this.firebaseStorage = firebaseStorage
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/di/AppModule.kt:64]: brilliant

File: app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt [hunk 4]
```diff
@@ -76,22 +82,20 @@ fun ItinerariesListScrollable(
...
         modifier = Modifier.padding(paddingValues).testTag(TestTags.ITINERARY_LIST_SCROLLABLE),
         verticalArrangement = spacedBy(15.dp)) {
-          // this.items(itineraries) { itinerary ->
           this.items(itineraries, { (iti) -> iti }) { itinerary ->
-            val isLikedInitially: Boolean
-            runBlocking {
-              isLikedInitially =
-                  profileViewModel.checkIfItineraryIsLiked(
-                      profileViewModel.getUserUid(), itinerary.uid)
+            val uid = firebaseAuth.currentUser?.uid ?: DEFAULT_USER_UID
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt:86]: This was changed out to avoid us having to use firebaseAuth.currentUser?.uid since the profile is set at sign-in.
See `profileViewModel` which has the function `getUserUid()` which is set to that of firebase.

File: app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt [hunk 5]
```diff
@@ -76,22 +82,20 @@ fun ItinerariesListScrollable(
...
+            var isLikedInitially by remember { mutableStateOf(false) }
+            LaunchedEffect(uid) {
+              isLikedInitially = profileViewModel.checkIfItineraryIsLiked(uid, itinerary.uid)
             }
 
             val onLikeButtonClick = { it: Itinerary, isLiked: Boolean ->
               if (isLiked) {
                 itineraryViewModel.decrementItineraryLikes(it)
-                profileViewModel.removeLikedItinerary(profileViewModel.getUserUid(), it.uid)
+                profileViewModel.removeLikedItinerary(uid, it.uid)
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt:95]: same here. Behavior doesn't match the new behavior.

File: app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt [hunk 6]
```diff
@@ -42,23 +45,32 @@ import androidx.compose.ui.text.style.TextAlign
...
-    isLikedInitially: Boolean = false
+    isLikedInitially: Boolean = false,
+    profileViewModel: ProfileViewModel,
+    imageRepository: ImageRepository
 ) {
 
-  val imageId = R.drawable.underground_2725336_1280
-
-  var isLiked by remember { mutableStateOf(isLikedInitially) }
+  val imageId = R.drawable.defaultitinerary
```
Comment (gunnm0) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt:63]: I don't like the name imageId why not call it defaultImage or imageNull?

File: app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt [hunk 7]
```diff
@@ -63,6 +64,7 @@ fun ProfileScreen(
     navHostController: NavHostController,
     firebaseAuth: FirebaseAuth
 ) {
+  Log.d("ProfileScreen", "ProfileScreen")
   val profile = profileViewModel.getActiveProfile()
   val currentUid = profileViewModel.getUserUid()
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt:69]: This behavior is inconsistent with the other screen (as I pointed out). This in fact is the correct new behavior

File: app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt [hunk 8]
```diff
@@ -76,22 +82,20 @@ fun ItinerariesListScrollable(
...
           this.items(itineraries, { (iti) -> iti }) { itinerary ->
-            val isLikedInitially: Boolean
-            runBlocking {
-              isLikedInitially =
-                  profileViewModel.checkIfItineraryIsLiked(
-                      profileViewModel.getUserUid(), itinerary.uid)
+            val uid = firebaseAuth.currentUser?.uid ?: DEFAULT_USER_UID
+            var isLikedInitially by remember { mutableStateOf(false) }
+            LaunchedEffect(uid) {
+              isLikedInitially = profileViewModel.checkIfItineraryIsLiked(uid, itinerary.uid)
```
Comment (gunnm0) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt:89]: I was there when you were changing it, I know you did well!

File: app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt [hunk 9]
```diff
@@ -169,16 +173,24 @@ fun WanderBadges() {
...
               .border(
                   BorderStroke(1.dp, MaterialTheme.colorScheme.inverseOnSurface),
                   shape = MaterialTheme.shapes.extraLarge)) {
+        val ownItineraries by
+            itineraryViewModel
+                .getUserItineraries(profile.userUid)
+                .collectAsState(initial = emptyList())
+        var score = 0
+        for (itinerary in ownItineraries) {
+          score += itinerary.numLikes * 10
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt:190]: Magic value `10` here. Is there a reason that this was chosen?

File: app/src/test/java/com/github/wanderwise_inc/app/di/AppModuleTest.kt
Comment (ethangraham2001) [inline app/src/test/java/com/github/wanderwise_inc/app/di/AppModuleTest.kt:1]: Looks good.

**Review by gunnm0 — COMMENTED** [review]
Good job, looks good. There are a lot of Logs in the code could you remove them?

File: app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt (hunk 6 above)
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt:63]: i will do that, thx for the comment.

File: app/build.gradle.kts [hunk 10]
```diff
@@ -195,6 +195,8 @@ dependencies {
     // --------------- Google Maps --------------------
     implementation("com.google.android.gms:play-services-maps:18.2.0")
     implementation("com.google.android.gms:play-services-location:21.2.0")
+    // ADDED THIS
```
[the remark this answers is not in the document]
Comment (engjellismaili) [reply app/build.gradle.kts:198]: will removed them

File: app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt [hunk 11]
```diff
@@ -107,7 +82,7 @@ class ImageRepositoryImpl(
             .putFile(it)
             .addOnSuccessListener { Log.d("STORE IMAGE", "STORE SUCCESS") }
             .addOnFailureListener {
-              Log.d("STORE IMAGE", "STORE FAILED")
+              Log.w("STORE IMAGE", "STORE FAILED")
               throw it
```
[the remark this answers is not in the document]
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt:86]: I don't really know, do you want me to remove them or ?

File: app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt [hunk 12]
```diff
@@ -37,7 +39,10 @@ class ProfileRepositoryImpl(db: FirebaseFirestore) : ProfileRepository {
             emit(null)
           }
         }
-        .catch { emit(null) }
+        .catch {
+          Log.w("ProfileRepositoryImpl", it)
```
[the remark this answers is not in the document]
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt:43]: yes, good catch, will do it

File: app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt (hunk 4 above)
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt:86]: Good remark, for coherence in the app this function should be called. Will fix that.

File: app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt (hunk 9 above)
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt:190]: No just didn't know what to add instead. Any thougths ?

File: app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt (hunk 11 above)
[the remark this answers is not in the document]
Comment (ethangraham2001) [reply app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt:86]: No it's good to keep them. Was just curious :) code is looking good and I think this is a good addition.

File: app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt (hunk 9 above)
Comment (ethangraham2001) [reply app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt:190]: honestly 10 sounds like a good number. Maybe throw it in a `const val WANDERSCORE_TO_LIKE_RATIO = 10` or something at the top of the file (or think of a better name haha)

File: app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt [hunk 13]
```diff
@@ -71,11 +41,13 @@ class ImageRepositoryImpl(
             val byteResult =
                 suspendCancellableCoroutine<ByteArray?> { continuation ->
                   profilePictureRef
-                      .getBytes(1024 * 1024)
```
Comment (imaneb942) [inline app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt:74]: is the goal of changing that to 2048 to get a better resolution?

File: app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt
Comment (imaneb942) [inline app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt:1]: The use of .catch { error -> ... } in flows is a good practice to ensure the application remains robust against exceptions. However, consider providing more detailed logging or handling strategies based on the type of exceptions.

File: app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepPreviewBanner.kt
Comment (imaneb942) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepPreviewBanner.kt:1]: we probably would want to change the dummyItinerary at some point

File: app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt
Comment (imaneb942) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/itinerary/ItineraryBanner.kt:1]: great additions!

File: app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt
Comment (imaneb942) [inline app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt:1]: tests look like they cover the expected behavior, sometimes simple is what works best :))

**Review by imaneb942 — COMMENTED** [review]
Great additions and thorought testings, are we sure that we won't have any issues regarding the merging with the main? from what I have heard there are some unexpected issues with the CI...

File: app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt [hunk 14]
```diff
@@ -187,7 +189,7 @@ fun WanderScore(profile: Profile, itineraryViewModel: ItineraryViewModel) {
                 .collectAsState(initial = emptyList())
         var score = 0
         for (itinerary in ownItineraries) {
-          score += itinerary.numLikes * 10
+          score += itinerary.numLikes * WANDER_POINTS_SCORE_MULTIPLIER
         }
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt:193]: Great. Clearer now

File: app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt [hunk 15]
```diff
@@ -83,7 +82,7 @@ fun ItinerariesListScrollable(
         modifier = Modifier.padding(paddingValues).testTag(TestTags.ITINERARY_LIST_SCROLLABLE),
         verticalArrangement = spacedBy(15.dp)) {
           this.items(itineraries, { (iti) -> iti }) { itinerary ->
-            val uid = firebaseAuth.currentUser?.uid ?: DEFAULT_USER_UID
+            val uid = profileViewModel.getUserUid()
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt:85]: Good stuff

File: app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt [hunk 16]
```diff
@@ -39,8 +39,8 @@ class ProfileRepositoryImpl(db: FirebaseFirestore) : ProfileRepository {
             emit(null)
           }
         }
-        .catch {
-          Log.w("ProfileRepositoryImpl", it)
+        .catch { error ->
+          Log.w("ProfileRepositoryImpl", error)
```
Comment (ethangraham2001) [inline app/src/main/java/com/github/wanderwise_inc/app/data/ProfileRepositoryImpl.kt:43]: clearer. Thx

**Review by ethangraham2001 — APPROVED** [review]
Thanks for addressing my comments

File: app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt (hunk 13 above)
Comment (engjellismaili) [reply app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt:74]: It's juste what can be fetched from Firebase. This can be changed whenever we want
